#!/usr/bin/env bash
#Write a Bash script that kills the process 7-highlander.
pid=$(pgrep -f 7-highlander)
if [[ ! -z "$pid" ]]; then
  kill "$pid"
  echo "Process 7-highlander with PID $pid has been stopped"
else
  echo "No instance of the 7-highlander process found."
fi
