#!/usr/bin/env bash
#a bash script that tells a story based on ect password

while IFS=: read -r username password userid groupid info home shell; do
  echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
