#!/usr/bin/env bash
#Write a Bash script that displays:
#The content of the current directory
#In a list format
for file in *; do
  if [[ ! $file =~ ^\..* ]]; then  # Skip hidden files
    echo "${file#*-}"
  fi
done
